version: '3.8'

services:
  app:
    build: .
    command: python main.py excel ./data/sample_file.xlsx
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

